# Generated by Django 4.2 on 2023-04-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='pets',
            field=models.ManyToManyField(blank=True, null=True, related_name='traits', to='pets.pet'),
        ),
    ]
